security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\User:
            algorithm: plaintext
            #algorithm: bcrypt
            #cost: 12

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_provider:
            id: App\Security\UserProvider

    access_decision_manager:
        strategy: unanimous

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            pattern: ^/
            anonymous: ~
            provider: user_provider
            form_login:
                use_forward: false
                login_path: login
                check_path: login_check
                default_target_path: homepage 
                always_use_default_target_path: true
                success_handler: App\Redirection\AfterLoginRedirection
                username_parameter: "form[_username]"
                password_parameter: "form[_password]"
            logout:
                path: logout
                target: login
            access_denied_url: frontend_app_bundle_default_homepage

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/confirm, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forgot, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration-success, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/nimda, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }  
