vich_uploader:
    db_driver: orm

    mappings:
        lesson_documents:
            uri_prefix: /uploads/lessons/documents
            upload_destination: '%kernel.project_dir%/public/uploads/lessons/documents'
