<?php

namespace App\Repository;

use App\Entity\User;

/**
 * ExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNotFinishedFor(User $user)
    {
        return $this->createQueryBuilder('e')
            ->andWhere('e.dateEnd IS NULL')
            ->andWhere('e.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}
