<?php

namespace App\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRandomQuestions($qty =30)
    {
	$all = $this->createQueryBuilder('q')
	    ->where('q.hide <> 1')
            ->getQuery()
            ->getResult()
        ;
        shuffle($all);

        return array_slice($all, 0, $qty);
    }
}
